- name: Check if Node Exporter exists in /usr/local/bin
  ansible.builtin.stat: "path=/usr/local/bin/node_exporter"
  register: check_path

- name: Download node exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
  when: not check_path.stat.exists

- name: Unarchive node exporter
  ansible.builtin.unarchive:
    remote_src: yes
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp
  when: not check_path.stat.exists

- name: Move node exporter to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx # 0755
  become: true
  when: not check_path.stat.exists

- name: Install unit file to systemd
  ansible.builtin.template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: u=rw # 0600
  become: true

- name: Configure systemd to use service
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter.service
  become: true
